# curl -X GET http://localhost:8080/health
GET http://localhost:8080/s3/health

###

# curl -F 'files=@/path-to-file/file.png'                                 http://localhost:8080/s3/upload
POST http://localhost:8080/s3/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="godfather.jpg"

< godfather.jpg
--WebAppBoundary--

###

# curl -X GET http://localhost:8080/s3/view-all
GET http://localhost:8080/s3/view-all

###

# curl -X GET http://localhost:8080/s3/view-all-db
GET http://localhost:8080/s3/view-all-db

###





